<?php
#AUTOGENERATED BY HYBRIDAUTH 2.1.1-dev INSTALLER - Monday 25th of March 2013 09:46:51 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return
    CMap::mergeArray(
        array(
             "base_url"   => "http://inposted.com/auth/oauth/",

             "providers"  => array(
                 // openid providers
                 "OpenID"     => array(
                     "enabled" => false,
                 ),

                 "AOL"        => array(
                     "enabled" => false
                 ),

                 "Yahoo"      => array(
                     "enabled" => false,
                     "keys"    => array("id" => "", "secret" => "")
                 ),

                 "Google"     => array(
                     "enabled" => true,
                     "keys"    => array("id" => "780779053189.apps.googleusercontent.com", "secret" => "xNa6k4ZqKlFp4m_EkRkk8gW9")
                 ),

                 "Facebook"   => array(
                     "enabled" => true,
                     "keys"    => array("id" => "394118874019792", "secret" => "02e988c289bcba3f22e6f432009996d7")
                 ),

                 "Twitter"    => array(
                     "enabled" => true,
                     "keys"    => array("key" => "yStdhQ4BPfKKqgKfLL7Sw", "secret" => "Yn6olXASLBkX16s6r22oqSXNxeyJScrnDgYARYy7rs")
                 ),

                 // windows live
                 "Live"       => array(
                     "enabled" => false,
                     "keys"    => array("id" => "", "secret" => "")
                 ),

                 "MySpace"    => array(
                     "enabled" => false,
                     "keys"    => array("key" => "", "secret" => "")
                 ),

                 "LinkedIn"   => array(
                     "enabled" => false,
                     "keys"    => array("key" => "", "secret" => "")
                 ),

                 "Foursquare" => array(
                     "enabled" => false,
                     "keys"    => array("id" => "", "secret" => "")
                 ),
             ),

             // if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
             "debug_mode" => false,

             "debug_file" => ""
        ), file_exists($local = __DIR__ . '/hoauth.local.php') ? require $local : []
    );
